-- ============================================================================
-- Cluster Health Agent - Snowflake Object Setup
-- ============================================================================
-- Run this script as ACCOUNTADMIN or a role with sufficient privileges.
--
-- Before running, update:
--   1. <YOUR_VERIFIED_EMAIL> — a verified email for receiving notifications
-- ============================================================================

-- 0. Use ACCOUNTADMIN for setup, then switch to dedicated role at the end
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS CLUSTER_HEALTH_AGENT_ROLE;
GRANT ROLE CLUSTER_HEALTH_AGENT_ROLE TO ROLE SYSADMIN;

-- 1. Database and Schema
CREATE DATABASE IF NOT EXISTS SPORTSBOOK_DW;
CREATE SCHEMA IF NOT EXISTS SPORTSBOOK_DW.WAGERS;

USE SCHEMA SPORTSBOOK_DW.WAGERS;

-- 2. BET_TRANSACTIONS table with clustering key
CREATE TABLE IF NOT EXISTS BET_TRANSACTIONS (
    BET_ID          NUMBER(38,0) NOT NULL,
    CUSTOMER_ID     NUMBER(38,0) NOT NULL,
    EVENT_ID        NUMBER(38,0) NOT NULL,
    SPORT           VARCHAR(50) NOT NULL,
    LEAGUE          VARCHAR(100),
    BET_TYPE        VARCHAR(30) NOT NULL,
    STAKE_AMOUNT    NUMBER(12,2) NOT NULL,
    ODDS            NUMBER(8,4) NOT NULL,
    POTENTIAL_PAYOUT NUMBER(14,2),
    BET_STATUS      VARCHAR(20) DEFAULT 'PENDING',
    PLACED_AT       TIMESTAMP_NTZ NOT NULL,
    SETTLED_AT      TIMESTAMP_NTZ,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (SPORT, PLACED_AT::DATE);

-- 3. NOTIFICATION_RECIPIENTS table
CREATE TABLE IF NOT EXISTS NOTIFICATION_RECIPIENTS (
    RECIPIENT_ID    NUMBER(38,0) AUTOINCREMENT,
    EMAIL           VARCHAR(256) NOT NULL,
    NAME            VARCHAR(256),
    ACTIVE          BOOLEAN DEFAULT TRUE,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Insert a default recipient (change <YOUR_VERIFIED_EMAIL> before running)
INSERT INTO NOTIFICATION_RECIPIENTS (EMAIL, NAME, ACTIVE)
SELECT '<YOUR_VERIFIED_EMAIL>', 'DW Admin', TRUE
WHERE NOT EXISTS (SELECT 1 FROM NOTIFICATION_RECIPIENTS WHERE EMAIL = '<YOUR_VERIFIED_EMAIL>');

-- 4. REMEDIATION_AUDIT table
CREATE TABLE IF NOT EXISTS REMEDIATION_AUDIT (
    AUDIT_ID                 NUMBER(38,0) AUTOINCREMENT,
    TABLE_NAME               VARCHAR(512) NOT NULL,
    ACTION                   VARCHAR(50) NOT NULL,
    BEFORE_AVERAGE_DEPTH     NUMBER(10,4),
    BEFORE_AVERAGE_OVERLAPS  NUMBER(10,4),
    AFTER_AVERAGE_DEPTH      NUMBER(10,4),
    AFTER_AVERAGE_OVERLAPS   NUMBER(10,4),
    DEPTH_IMPROVEMENT_PCT    NUMBER(8,2),
    OVERLAP_IMPROVEMENT_PCT  NUMBER(8,2),
    STATUS                   VARCHAR(20) NOT NULL,
    ERROR_MESSAGE            VARCHAR(4096),
    EXECUTED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. Synthetic data load (5M rows)
-- Uses a generator to create realistic sportsbook betting data
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE UNIFORM(1, 6, RANDOM())
        WHEN 1 THEN 'NFL'
        WHEN 2 THEN 'NBA'
        WHEN 3 THEN 'MLB'
        WHEN 4 THEN 'NHL'
        WHEN 5 THEN 'SOCCER'
        ELSE 'MMA'
    END AS SPORT,
    CASE UNIFORM(1, 6, RANDOM())
        WHEN 1 THEN 'National Football League'
        WHEN 2 THEN 'National Basketball Association'
        WHEN 3 THEN 'Major League Baseball'
        WHEN 4 THEN 'National Hockey League'
        WHEN 5 THEN 'English Premier League'
        ELSE 'Ultimate Fighting Championship'
    END AS LEAGUE,
    CASE UNIFORM(1, 5, RANDOM())
        WHEN 1 THEN 'MONEYLINE'
        WHEN 2 THEN 'SPREAD'
        WHEN 3 THEN 'OVER_UNDER'
        WHEN 4 THEN 'PARLAY'
        ELSE 'PROP'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE UNIFORM(1, 4, RANDOM())
        WHEN 1 THEN 'WON'
        WHEN 2 THEN 'LOST'
        WHEN 3 THEN 'PENDING'
        ELSE 'VOID'
    END AS BET_STATUS,
    DATEADD('second',
        -UNIFORM(0, 86400 * 365, RANDOM()),
        CURRENT_TIMESTAMP()
    ) AS PLACED_AT,
    CASE
        WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT)
        ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 5000000));

-- 6. Notification Integration (email type)
-- NOTE: Change <YOUR_VERIFIED_EMAIL> to your actual verified email address
CREATE NOTIFICATION INTEGRATION IF NOT EXISTS CLUSTER_HEALTH_EMAIL_INTEGRATION
    TYPE = EMAIL
    ENABLED = TRUE
    ALLOWED_RECIPIENTS = ('<YOUR_VERIFIED_EMAIL>');

-- 7. Warehouse for the agent
CREATE WAREHOUSE IF NOT EXISTS CLUSTER_HEALTH_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- 8. Compute Pool for SPCS
CREATE COMPUTE POOL IF NOT EXISTS CLUSTER_HEALTH_POOL
    MIN_NODES = 1
    MAX_NODES = 1
    INSTANCE_FAMILY = CPU_X64_XS;

-- 9. Image Repository
CREATE IMAGE REPOSITORY IF NOT EXISTS SPORTSBOOK_DW.WAGERS.CLUSTER_HEALTH_REPO;


-- 10. Internal Stage for service spec
CREATE STAGE IF NOT EXISTS SPORTSBOOK_DW.WAGERS.CLUSTER_HEALTH_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- 11. Service (after uploading spec and image)
-- PUT file://deploy/service_spec.yaml @CLUSTER_HEALTH_STAGE AUTO_COMPRESS=FALSE;
--
-- CREATE SERVICE IF NOT EXISTS CLUSTER_HEALTH_SERVICE
--     IN COMPUTE POOL CLUSTER_HEALTH_POOL
--     FROM @CLUSTER_HEALTH_STAGE
--     SPECIFICATION_FILE = 'service_spec.yaml'
--     EXTERNAL_ACCESS_INTEGRATIONS = ()
--     MIN_INSTANCES = 1
--     MAX_INSTANCES = 1;

-- 12. Service Function + Scheduled Task (5-minute interval)
-- Uncomment after the service is running
--
-- CREATE OR REPLACE FUNCTION SPORTSBOOK_DW.WAGERS.TRIGGER_HEALTH_CHECK()
--     RETURNS VARCHAR
--     SERVICE = SPORTSBOOK_DW.WAGERS.CLUSTER_HEALTH_SERVICE
--     ENDPOINT = 'cluster-health-endpoint'
--     AS '/health-check';
--
-- CREATE OR REPLACE TASK CLUSTER_HEALTH_CHECK_TASK
--     WAREHOUSE = CLUSTER_HEALTH_WH
--     SCHEDULE = '5 MINUTE'
-- AS
--     SELECT SPORTSBOOK_DW.WAGERS.TRIGGER_HEALTH_CHECK();
--
-- ALTER TASK CLUSTER_HEALTH_CHECK_TASK RESUME;

-- 13. Grants to the dedicated role
GRANT USAGE ON DATABASE SPORTSBOOK_DW TO ROLE CLUSTER_HEALTH_AGENT_ROLE;
GRANT USAGE ON SCHEMA SPORTSBOOK_DW.WAGERS TO ROLE CLUSTER_HEALTH_AGENT_ROLE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA SPORTSBOOK_DW.WAGERS TO ROLE CLUSTER_HEALTH_AGENT_ROLE;
GRANT USAGE ON WAREHOUSE CLUSTER_HEALTH_WH TO ROLE CLUSTER_HEALTH_AGENT_ROLE;
GRANT USAGE ON COMPUTE POOL CLUSTER_HEALTH_POOL TO ROLE CLUSTER_HEALTH_AGENT_ROLE;
GRANT READ, WRITE ON IMAGE REPOSITORY SPORTSBOOK_DW.WAGERS.CLUSTER_HEALTH_REPO TO ROLE CLUSTER_HEALTH_AGENT_ROLE;
GRANT READ, WRITE ON STAGE SPORTSBOOK_DW.WAGERS.CLUSTER_HEALTH_STAGE TO ROLE CLUSTER_HEALTH_AGENT_ROLE;
GRANT USAGE ON INTEGRATION CLUSTER_HEALTH_EMAIL_INTEGRATION TO ROLE CLUSTER_HEALTH_AGENT_ROLE;

-- 14. Switch to the project role for subsequent operations
USE ROLE CLUSTER_HEALTH_AGENT_ROLE;