-- ============================================================================
-- Load Degraded Clustering Data
-- ============================================================================
-- Purpose: Insert synthetic bet data in an anti-clustered order to degrade
-- the clustering quality of BET_TRANSACTIONS, forcing the health agent to
-- detect unhealthy clustering (average_depth > 5, average_overlaps > 10).
--
-- The table is clustered by (SPORT, PLACED_AT::DATE). This script inserts
-- 20 batches of 500K rows each (10M total) with fully randomized sport and
-- date values in each batch, ensuring micro-partitions contain mixed
-- clustering key values.
--
-- Usage:
--   Execute this script in a Snowflake worksheet or via snow CLI:
--   snow sql -c <YOUR_CONNECTION> --role ACCOUNTADMIN -f sql/load_degraded_data.sql
--
-- After running, verify degradation:
--   SELECT SYSTEM$CLUSTERING_INFORMATION('SPORTSBOOK_DW.WAGERS.BET_TRANSACTIONS');
--   Expected: average_depth > 5, average_overlaps > 10
-- ============================================================================

USE SCHEMA SPORTSBOOK_DW.WAGERS;

-- Batch 1 of 20 (500K rows, randomized sport + date order)
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 5000000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'NFL' WHEN 1 THEN 'NBA' WHEN 2 THEN 'MLB'
        WHEN 3 THEN 'NHL' WHEN 4 THEN 'SOCCER' ELSE 'MMA'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'National Football League' WHEN 1 THEN 'National Basketball Association'
        WHEN 2 THEN 'Major League Baseball' WHEN 3 THEN 'National Hockey League'
        WHEN 4 THEN 'English Premier League' ELSE 'Ultimate Fighting Championship'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'MONEYLINE' WHEN 1 THEN 'SPREAD' WHEN 2 THEN 'OVER_UNDER'
        WHEN 3 THEN 'PARLAY' ELSE 'PROP'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'WON' WHEN 1 THEN 'LOST' WHEN 2 THEN 'PENDING' ELSE 'VOID'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 2 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 5500000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'NBA' WHEN 1 THEN 'MMA' WHEN 2 THEN 'NFL'
        WHEN 3 THEN 'SOCCER' WHEN 4 THEN 'NHL' ELSE 'MLB'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'National Basketball Association' WHEN 1 THEN 'Ultimate Fighting Championship'
        WHEN 2 THEN 'National Football League' WHEN 3 THEN 'English Premier League'
        WHEN 4 THEN 'National Hockey League' ELSE 'Major League Baseball'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'PROP' WHEN 1 THEN 'MONEYLINE' WHEN 2 THEN 'PARLAY'
        WHEN 3 THEN 'SPREAD' ELSE 'OVER_UNDER'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'LOST' WHEN 1 THEN 'WON' WHEN 2 THEN 'VOID' ELSE 'PENDING'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 3 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 6000000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'SOCCER' WHEN 1 THEN 'NFL' WHEN 2 THEN 'MMA'
        WHEN 3 THEN 'NBA' WHEN 4 THEN 'MLB' ELSE 'NHL'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'English Premier League' WHEN 1 THEN 'National Football League'
        WHEN 2 THEN 'Ultimate Fighting Championship' WHEN 3 THEN 'National Basketball Association'
        WHEN 4 THEN 'Major League Baseball' ELSE 'National Hockey League'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'OVER_UNDER' WHEN 1 THEN 'PROP' WHEN 2 THEN 'MONEYLINE'
        WHEN 3 THEN 'PARLAY' ELSE 'SPREAD'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'PENDING' WHEN 1 THEN 'VOID' WHEN 2 THEN 'WON' ELSE 'LOST'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 4 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 6500000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'MMA' WHEN 1 THEN 'SOCCER' WHEN 2 THEN 'NHL'
        WHEN 3 THEN 'NFL' WHEN 4 THEN 'NBA' ELSE 'MLB'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'Ultimate Fighting Championship' WHEN 1 THEN 'English Premier League'
        WHEN 2 THEN 'National Hockey League' WHEN 3 THEN 'National Football League'
        WHEN 4 THEN 'National Basketball Association' ELSE 'Major League Baseball'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'SPREAD' WHEN 1 THEN 'OVER_UNDER' WHEN 2 THEN 'PROP'
        WHEN 3 THEN 'MONEYLINE' ELSE 'PARLAY'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'WON' WHEN 1 THEN 'PENDING' WHEN 2 THEN 'LOST' ELSE 'VOID'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 5 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 7000000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'NHL' WHEN 1 THEN 'MLB' WHEN 2 THEN 'SOCCER'
        WHEN 3 THEN 'MMA' WHEN 4 THEN 'NFL' ELSE 'NBA'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'National Hockey League' WHEN 1 THEN 'Major League Baseball'
        WHEN 2 THEN 'English Premier League' WHEN 3 THEN 'Ultimate Fighting Championship'
        WHEN 4 THEN 'National Football League' ELSE 'National Basketball Association'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'PARLAY' WHEN 1 THEN 'SPREAD' WHEN 2 THEN 'OVER_UNDER'
        WHEN 3 THEN 'PROP' ELSE 'MONEYLINE'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'VOID' WHEN 1 THEN 'LOST' WHEN 2 THEN 'PENDING' ELSE 'WON'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 6 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 7500000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'MLB' WHEN 1 THEN 'NHL' WHEN 2 THEN 'NBA'
        WHEN 3 THEN 'SOCCER' WHEN 4 THEN 'MMA' ELSE 'NFL'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'Major League Baseball' WHEN 1 THEN 'National Hockey League'
        WHEN 2 THEN 'National Basketball Association' WHEN 3 THEN 'English Premier League'
        WHEN 4 THEN 'Ultimate Fighting Championship' ELSE 'National Football League'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'MONEYLINE' WHEN 1 THEN 'PARLAY' WHEN 2 THEN 'SPREAD'
        WHEN 3 THEN 'OVER_UNDER' ELSE 'PROP'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'LOST' WHEN 1 THEN 'WON' WHEN 2 THEN 'VOID' ELSE 'PENDING'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 7 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 8000000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'NFL' WHEN 1 THEN 'MMA' WHEN 2 THEN 'MLB'
        WHEN 3 THEN 'NHL' WHEN 4 THEN 'SOCCER' ELSE 'NBA'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'National Football League' WHEN 1 THEN 'Ultimate Fighting Championship'
        WHEN 2 THEN 'Major League Baseball' WHEN 3 THEN 'National Hockey League'
        WHEN 4 THEN 'English Premier League' ELSE 'National Basketball Association'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'PROP' WHEN 1 THEN 'MONEYLINE' WHEN 2 THEN 'PARLAY'
        WHEN 3 THEN 'SPREAD' ELSE 'OVER_UNDER'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'PENDING' WHEN 1 THEN 'WON' WHEN 2 THEN 'LOST' ELSE 'VOID'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 8 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 8500000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'SOCCER' WHEN 1 THEN 'NBA' WHEN 2 THEN 'NFL'
        WHEN 3 THEN 'MLB' WHEN 4 THEN 'MMA' ELSE 'NHL'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'English Premier League' WHEN 1 THEN 'National Basketball Association'
        WHEN 2 THEN 'National Football League' WHEN 3 THEN 'Major League Baseball'
        WHEN 4 THEN 'Ultimate Fighting Championship' ELSE 'National Hockey League'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'OVER_UNDER' WHEN 1 THEN 'SPREAD' WHEN 2 THEN 'MONEYLINE'
        WHEN 3 THEN 'PROP' ELSE 'PARLAY'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'WON' WHEN 1 THEN 'VOID' WHEN 2 THEN 'PENDING' ELSE 'LOST'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 9 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 9000000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'MMA' WHEN 1 THEN 'NFL' WHEN 2 THEN 'SOCCER'
        WHEN 3 THEN 'NBA' WHEN 4 THEN 'MLB' ELSE 'NHL'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'Ultimate Fighting Championship' WHEN 1 THEN 'National Football League'
        WHEN 2 THEN 'English Premier League' WHEN 3 THEN 'National Basketball Association'
        WHEN 4 THEN 'Major League Baseball' ELSE 'National Hockey League'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'SPREAD' WHEN 1 THEN 'PROP' WHEN 2 THEN 'OVER_UNDER'
        WHEN 3 THEN 'MONEYLINE' ELSE 'PARLAY'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'LOST' WHEN 1 THEN 'PENDING' WHEN 2 THEN 'WON' ELSE 'VOID'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 10 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 9500000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'NBA' WHEN 1 THEN 'SOCCER' WHEN 2 THEN 'NHL'
        WHEN 3 THEN 'MMA' WHEN 4 THEN 'NFL' ELSE 'MLB'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'National Basketball Association' WHEN 1 THEN 'English Premier League'
        WHEN 2 THEN 'National Hockey League' WHEN 3 THEN 'Ultimate Fighting Championship'
        WHEN 4 THEN 'National Football League' ELSE 'Major League Baseball'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'PARLAY' WHEN 1 THEN 'OVER_UNDER' WHEN 2 THEN 'SPREAD'
        WHEN 3 THEN 'PROP' ELSE 'MONEYLINE'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'VOID' WHEN 1 THEN 'LOST' WHEN 2 THEN 'WON' ELSE 'PENDING'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 11 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 10000000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'NHL' WHEN 1 THEN 'MLB' WHEN 2 THEN 'MMA'
        WHEN 3 THEN 'SOCCER' WHEN 4 THEN 'NBA' ELSE 'NFL'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'National Hockey League' WHEN 1 THEN 'Major League Baseball'
        WHEN 2 THEN 'Ultimate Fighting Championship' WHEN 3 THEN 'English Premier League'
        WHEN 4 THEN 'National Basketball Association' ELSE 'National Football League'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'MONEYLINE' WHEN 1 THEN 'PARLAY' WHEN 2 THEN 'PROP'
        WHEN 3 THEN 'SPREAD' ELSE 'OVER_UNDER'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'WON' WHEN 1 THEN 'LOST' WHEN 2 THEN 'VOID' ELSE 'PENDING'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 12 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 10500000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'MLB' WHEN 1 THEN 'NFL' WHEN 2 THEN 'NBA'
        WHEN 3 THEN 'NHL' WHEN 4 THEN 'MMA' ELSE 'SOCCER'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'Major League Baseball' WHEN 1 THEN 'National Football League'
        WHEN 2 THEN 'National Basketball Association' WHEN 3 THEN 'National Hockey League'
        WHEN 4 THEN 'Ultimate Fighting Championship' ELSE 'English Premier League'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'OVER_UNDER' WHEN 1 THEN 'MONEYLINE' WHEN 2 THEN 'SPREAD'
        WHEN 3 THEN 'PARLAY' ELSE 'PROP'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'PENDING' WHEN 1 THEN 'WON' WHEN 2 THEN 'LOST' ELSE 'VOID'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 13 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 11000000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'SOCCER' WHEN 1 THEN 'MMA' WHEN 2 THEN 'NHL'
        WHEN 3 THEN 'MLB' WHEN 4 THEN 'NFL' ELSE 'NBA'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'English Premier League' WHEN 1 THEN 'Ultimate Fighting Championship'
        WHEN 2 THEN 'National Hockey League' WHEN 3 THEN 'Major League Baseball'
        WHEN 4 THEN 'National Football League' ELSE 'National Basketball Association'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'PROP' WHEN 1 THEN 'SPREAD' WHEN 2 THEN 'PARLAY'
        WHEN 3 THEN 'OVER_UNDER' ELSE 'MONEYLINE'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'LOST' WHEN 1 THEN 'VOID' WHEN 2 THEN 'PENDING' ELSE 'WON'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 14 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 11500000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'NBA' WHEN 1 THEN 'NHL' WHEN 2 THEN 'SOCCER'
        WHEN 3 THEN 'NFL' WHEN 4 THEN 'MLB' ELSE 'MMA'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'National Basketball Association' WHEN 1 THEN 'National Hockey League'
        WHEN 2 THEN 'English Premier League' WHEN 3 THEN 'National Football League'
        WHEN 4 THEN 'Major League Baseball' ELSE 'Ultimate Fighting Championship'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'MONEYLINE' WHEN 1 THEN 'PROP' WHEN 2 THEN 'OVER_UNDER'
        WHEN 3 THEN 'SPREAD' ELSE 'PARLAY'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'WON' WHEN 1 THEN 'PENDING' WHEN 2 THEN 'VOID' ELSE 'LOST'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 15 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 12000000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'MMA' WHEN 1 THEN 'SOCCER' WHEN 2 THEN 'NFL'
        WHEN 3 THEN 'NBA' WHEN 4 THEN 'NHL' ELSE 'MLB'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'Ultimate Fighting Championship' WHEN 1 THEN 'English Premier League'
        WHEN 2 THEN 'National Football League' WHEN 3 THEN 'National Basketball Association'
        WHEN 4 THEN 'National Hockey League' ELSE 'Major League Baseball'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'SPREAD' WHEN 1 THEN 'MONEYLINE' WHEN 2 THEN 'PROP'
        WHEN 3 THEN 'PARLAY' ELSE 'OVER_UNDER'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'VOID' WHEN 1 THEN 'WON' WHEN 2 THEN 'LOST' ELSE 'PENDING'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 16 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 12500000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'NFL' WHEN 1 THEN 'NBA' WHEN 2 THEN 'MMA'
        WHEN 3 THEN 'MLB' WHEN 4 THEN 'SOCCER' ELSE 'NHL'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'National Football League' WHEN 1 THEN 'National Basketball Association'
        WHEN 2 THEN 'Ultimate Fighting Championship' WHEN 3 THEN 'Major League Baseball'
        WHEN 4 THEN 'English Premier League' ELSE 'National Hockey League'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'PARLAY' WHEN 1 THEN 'OVER_UNDER' WHEN 2 THEN 'MONEYLINE'
        WHEN 3 THEN 'PROP' ELSE 'SPREAD'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'PENDING' WHEN 1 THEN 'LOST' WHEN 2 THEN 'WON' ELSE 'VOID'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 17 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 13000000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'NHL' WHEN 1 THEN 'SOCCER' WHEN 2 THEN 'NBA'
        WHEN 3 THEN 'MMA' WHEN 4 THEN 'MLB' ELSE 'NFL'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'National Hockey League' WHEN 1 THEN 'English Premier League'
        WHEN 2 THEN 'National Basketball Association' WHEN 3 THEN 'Ultimate Fighting Championship'
        WHEN 4 THEN 'Major League Baseball' ELSE 'National Football League'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'OVER_UNDER' WHEN 1 THEN 'PARLAY' WHEN 2 THEN 'SPREAD'
        WHEN 3 THEN 'MONEYLINE' ELSE 'PROP'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'LOST' WHEN 1 THEN 'PENDING' WHEN 2 THEN 'VOID' ELSE 'WON'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 18 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 13500000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'MLB' WHEN 1 THEN 'MMA' WHEN 2 THEN 'SOCCER'
        WHEN 3 THEN 'NFL' WHEN 4 THEN 'NBA' ELSE 'NHL'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'Major League Baseball' WHEN 1 THEN 'Ultimate Fighting Championship'
        WHEN 2 THEN 'English Premier League' WHEN 3 THEN 'National Football League'
        WHEN 4 THEN 'National Basketball Association' ELSE 'National Hockey League'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'MONEYLINE' WHEN 1 THEN 'SPREAD' WHEN 2 THEN 'PARLAY'
        WHEN 3 THEN 'OVER_UNDER' ELSE 'PROP'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'WON' WHEN 1 THEN 'VOID' WHEN 2 THEN 'LOST' ELSE 'PENDING'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 19 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 14000000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'SOCCER' WHEN 1 THEN 'NFL' WHEN 2 THEN 'NHL'
        WHEN 3 THEN 'MLB' WHEN 4 THEN 'MMA' ELSE 'NBA'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'English Premier League' WHEN 1 THEN 'National Football League'
        WHEN 2 THEN 'National Hockey League' WHEN 3 THEN 'Major League Baseball'
        WHEN 4 THEN 'Ultimate Fighting Championship' ELSE 'National Basketball Association'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'PROP' WHEN 1 THEN 'MONEYLINE' WHEN 2 THEN 'OVER_UNDER'
        WHEN 3 THEN 'SPREAD' ELSE 'PARLAY'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'PENDING' WHEN 1 THEN 'WON' WHEN 2 THEN 'VOID' ELSE 'LOST'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Batch 20 of 20
INSERT INTO BET_TRANSACTIONS (
    BET_ID, CUSTOMER_ID, EVENT_ID, SPORT, LEAGUE, BET_TYPE,
    STAKE_AMOUNT, ODDS, POTENTIAL_PAYOUT, BET_STATUS, PLACED_AT, SETTLED_AT
)
SELECT
    SEQ4() + 14500000 AS BET_ID,
    UNIFORM(1, 100000, RANDOM()) AS CUSTOMER_ID,
    UNIFORM(1, 5000, RANDOM()) AS EVENT_ID,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'NBA' WHEN 1 THEN 'MLB' WHEN 2 THEN 'MMA'
        WHEN 3 THEN 'SOCCER' WHEN 4 THEN 'NHL' ELSE 'NFL'
    END AS SPORT,
    CASE MOD(ABS(RANDOM()), 6)
        WHEN 0 THEN 'National Basketball Association' WHEN 1 THEN 'Major League Baseball'
        WHEN 2 THEN 'Ultimate Fighting Championship' WHEN 3 THEN 'English Premier League'
        WHEN 4 THEN 'National Hockey League' ELSE 'National Football League'
    END AS LEAGUE,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'SPREAD' WHEN 1 THEN 'PROP' WHEN 2 THEN 'MONEYLINE'
        WHEN 3 THEN 'PARLAY' ELSE 'OVER_UNDER'
    END AS BET_TYPE,
    ROUND(UNIFORM(5, 5000, RANDOM())::NUMBER(12,2) / 100, 2) AS STAKE_AMOUNT,
    ROUND(UNIFORM(100, 2000, RANDOM())::NUMBER(8,4) / 100, 4) AS ODDS,
    ROUND(STAKE_AMOUNT * ODDS, 2) AS POTENTIAL_PAYOUT,
    CASE MOD(ABS(RANDOM()), 4)
        WHEN 0 THEN 'VOID' WHEN 1 THEN 'PENDING' WHEN 2 THEN 'WON' ELSE 'LOST'
    END AS BET_STATUS,
    DATEADD('second', -UNIFORM(0, 86400 * 730, RANDOM()), CURRENT_TIMESTAMP()) AS PLACED_AT,
    CASE WHEN BET_STATUS IN ('WON', 'LOST', 'VOID')
        THEN DATEADD('hour', UNIFORM(1, 72, RANDOM()), PLACED_AT) ELSE NULL
    END AS SETTLED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 500000));

-- Verify clustering degradation
SELECT SYSTEM$CLUSTERING_INFORMATION('SPORTSBOOK_DW.WAGERS.BET_TRANSACTIONS');
